---
  - name: "Update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: "Upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: "Remove dependencies no longer needed"
    become: true
    apt:
      autoremove: yes

  - name: Install Dependencies
    become: true
    apt: 
      name: ['nodejs', 'npm']
      state: latest
      update_cache: yes
  
  - name: Install pm2
    become: true
    npm: 
      name: pm2 
      global: yes 
      production: yes

