---
  - name: "Update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: "Upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: "Remove dependencies no longer needed"
    become: true
    apt:
      autoremove: yes

  - name: Install Dependencies
    become: true
    apt: 
      name: ['nodejs', 'npm']
      state: latest
      update_cache: yes     
  
  - name: Install pm2
    become: true
    npm: 
      name: pm2 
      global: yes 
      production: yes

  - name: Create Application Directory
    file:
      path: /home/ubuntu/nodeapp
      state: directory
  
  - name: Install Index JS
    copy:
      src: index.js
      dest: /home/ubuntu/nodeapp/index.js
      backup: yes

  - name: Stop Application
    become: yes
    command: pm2 stop nodeapp 
    args: 
      chdir: /home/ubuntu/nodeapp
    ignore_errors: yes

  - name: Start Application
    become: yes
    command: pm2 start index.js --name nodeapp 
    args: 
      chdir: /home/ubuntu/nodeapp

